bot:
  token:
  username:

telegram:
  proxy:
    port: 9150
    host: 127.0.0.1
    type: socks5
  channel-name:
  sync-file-name: last-parse-info

website:
  url: https://xn--80aesfpebagmfblc0a.xn--p1ai/

scheduler:
  delay: 300000

message:
  footer: via стопкоронавирус.рф